services:
  erddap:
    image: axiom/docker-erddap:2.23-jdk17-openjdk
    ports:
      - 8988:8080
    volumes:
      - ./datasets.d.remote:/datasets.d:ro
    environment:
      ERDDAP_baseUrl: http://estuaries03.axiomptk:8080
      ERDDAP_baseHttpsUrl: https://estuaries03.axiomptk:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/erddap/tabledap/cwwcNDBCMet.html"]
      interval: 5s
      timeout: 2s
      retries: 100
  nginx:
    image: nginx:1.25
    ports:
      - 8080:80
    volumes:
      - ./nginx-server.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      erddap:
        condition: service_healthy
  erddap-proxy:
    image: axiom/docker-erddap:2.23-jdk17-openjdk
    ports:
      - 8989:8080
    environment:
      ERDDAP_baseUrl: http://estuaries03.axiomptk:8989
      ERDDAP_baseHttpsUrl: https://estuaries03.axiomptk:8989
    volumes:
      - ./datasets.d:/datasets.d:ro
    depends_on:
      - nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/erddap/tabledap/cwwcNDBCMet-remote.html"]
      interval: 5s
      timeout: 2s
      retries: 100
  erddap-requests:
    image: axiom/docker-erddap:2.23-jdk17-openjdk
    volumes:
      - ./erddap-requests.sh:/erddap-requests.sh:ro
    command: /bin/bash /erddap-requests.sh
    depends_on:
      erddap-proxy:
        condition: service_healthy
